package playback

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/jakethecake75/cmediastack/internal/library"
)

// These tests run against REAL media, generated by ffmpeg, and probed by the
// real ffprobe through the real sandbox.
//
// Fixtures were considered and rejected. A fixture of ffprobe's JSON tests this
// package's parsing against a string its author wrote, which is exactly the
// mistake ADR-0018 records from the metadata client: the field names came from
// documentation and two of them were wrong. What matters here is what ffprobe
// on this machine actually emits for a file that actually exists.

// haveFFmpeg skips when the tools are absent, so the suite stays runnable on a
// machine without them.
func haveFFmpeg(t *testing.T) {
	t.Helper()
	for _, tool := range []string{FFmpegPath, FFprobePath} {
		if _, err := exec.LookPath(tool); err != nil {
			t.Skipf("%s is not installed", tool)
		}
	}
}

// generate builds a media file and returns its path, skipping if this ffmpeg
// build cannot produce what was asked for. Encoder availability varies between
// distributions far more than people expect, and a test that fails because a
// codec was not compiled in is noise rather than a defect.
//
// These fixtures use mpeg4 and ffv1 rather than h264 — not because h264 is
// unavailable, but because what is being tested is this package's READING of
// what ffprobe reports, and the cheapest encoder that produces a real container
// with real stream metadata tests that exactly as well.
func generate(t *testing.T, name string, args ...string) string {
	t.Helper()
	haveFFmpeg(t)
	path := filepath.Join(t.TempDir(), name)
	full := append([]string{"-loglevel", "error", "-y"}, args...)
	full = append(full, path)
	out, err := exec.CommandContext(t.Context(), FFmpegPath, full...).CombinedOutput()
	if err != nil {
		t.Skipf("this ffmpeg cannot produce %s (%v): %s", name, err, firstLine(out))
	}
	return path
}

func probeFile(t *testing.T, path string) Probe {
	t.Helper()
	s := quietSandbox(t)
	f, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()

	p, err := NewProber(s).Probe(context.Background(), f)
	if err != nil {
		t.Fatalf("probing %s: %v", filepath.Base(path), err)
	}
	return p
}

// The base case, against a file whose contents are known because this test
// created them.
func TestAProbeReportsWhatIsActuallyInTheFile(t *testing.T) {
	path := generate(t, "basic.mp4",
		"-f", "lavfi", "-i", "testsrc=duration=3:size=640x360:rate=25",
		"-f", "lavfi", "-i", "sine=frequency=440:duration=3",
		"-c:v", "mpeg4", "-q:v", "5", "-c:a", "aac", "-ac", "2")

	p := probeFile(t, path)

	if !strings.Contains(p.Container, "mp4") {
		t.Errorf("container = %q, want something naming mp4", p.Container)
	}
	// Duration is compared loosely: encoders round, and asserting equality
	// would be asserting a property of ffmpeg rather than of this code.
	if p.Duration < 2500*time.Millisecond || p.Duration > 3500*time.Millisecond {
		t.Errorf("duration = %s, want about 3s", p.Duration)
	}
	if len(p.Video) != 1 {
		t.Fatalf("%d video streams, want 1: %+v", len(p.Video), p.Video)
	}
	v := p.Video[0]
	if v.Width != 640 || v.Height != 360 {
		t.Errorf("%dx%d, want 640x360", v.Width, v.Height)
	}
	if v.Codec != "mpeg4" {
		t.Errorf("codec = %q", v.Codec)
	}
	if v.BitDepth != 8 {
		t.Errorf("bit depth = %d, want 8", v.BitDepth)
	}
	if v.FrameRate < 24 || v.FrameRate > 26 {
		t.Errorf("frame rate = %v, want about 25", v.FrameRate)
	}
	if v.HDR {
		t.Error("an SDR test pattern was reported as HDR")
	}
	if len(p.Audio) != 1 {
		t.Fatalf("%d audio streams, want 1", len(p.Audio))
	}
	if p.Audio[0].Channels != 2 {
		t.Errorf("channels = %d, want 2", p.Audio[0].Channels)
	}
	if p.SizeBytes <= 0 || p.ModTime.IsZero() {
		t.Errorf("the probe did not record the file's identity: size=%d mod=%v",
			p.SizeBytes, p.ModTime)
	}
}

// ADR-0005 turns on this flag: HDR direct-plays on the target hardware or it
// does not play, so getting it wrong in either direction is a visible failure.
func TestHDRIsDetectedFromTheTransferFunction(t *testing.T) {
	path := generate(t, "hdr.mp4",
		"-f", "lavfi", "-i", "testsrc=duration=2:size=320x180:rate=25",
		"-c:v", "mpeg4", "-q:v", "5",
		"-pix_fmt", "yuv420p",
		"-color_trc", "smpte2084",
		"-color_primaries", "bt2020",
		"-colorspace", "bt2020nc")

	p := probeFile(t, path)
	if len(p.Video) != 1 {
		t.Fatalf("%d video streams", len(p.Video))
	}
	v := p.Video[0]
	if v.ColorTransfer != "smpte2084" {
		t.Skipf("this ffmpeg did not write the transfer function (got %q), so "+
			"there is nothing to detect", v.ColorTransfer)
	}
	if !v.HDR {
		t.Errorf("a smpte2084 stream was not reported as HDR: %+v", v)
	}
}

// The false positive this code was written to avoid. bt2020 PRIMARIES appear on
// plenty of SDR content; treating them as HDR would refuse to play files that
// play perfectly well, which on an i5-6500T is the expensive direction to be
// wrong in.
func TestWideColourPrimariesAloneDoNotMeanHDR(t *testing.T) {
	path := generate(t, "wide-sdr.mp4",
		"-f", "lavfi", "-i", "testsrc=duration=2:size=320x180:rate=25",
		"-c:v", "mpeg4", "-q:v", "5",
		"-pix_fmt", "yuv420p",
		"-color_trc", "bt709",
		"-color_primaries", "bt2020",
		"-colorspace", "bt2020nc")

	p := probeFile(t, path)
	if len(p.Video) != 1 {
		t.Fatalf("%d video streams", len(p.Video))
	}
	v := p.Video[0]
	if v.ColorPrimaries != "bt2020" {
		t.Skipf("this ffmpeg did not write bt2020 primaries (got %q)", v.ColorPrimaries)
	}
	if v.HDR {
		t.Errorf("bt2020 primaries with a bt709 transfer were called HDR: %+v — "+
			"this refuses to play files that would have played", v)
	}
}

// Bit depth decides whether the target hardware can decode at all, and pix_fmt
// is where it is stated reliably.
func TestBitDepthComesFromThePixelFormat(t *testing.T) {
	path := generate(t, "tenbit.mkv",
		"-f", "lavfi", "-i", "testsrc=duration=2:size=320x180:rate=25",
		"-c:v", "ffv1", "-pix_fmt", "yuv420p10le")

	p := probeFile(t, path)
	if len(p.Video) != 1 {
		t.Fatalf("%d video streams", len(p.Video))
	}
	if got := p.Video[0]; got.BitDepth != 10 {
		t.Errorf("bit depth = %d for pix_fmt %q, want 10", got.BitDepth, got.PixelFormat)
	}
}

// A text track can be handed to a browser; a bitmap track can only be drawn
// onto the picture, which is a transcode and on this hardware may mean it
// cannot be shown at all. Conflating them produces subtitles that silently
// never appear.
func TestASubtitleTrackSaysWhetherItIsTextOrPictures(t *testing.T) {
	dir := t.TempDir()
	srt := filepath.Join(dir, "s.srt")
	if err := os.WriteFile(srt, []byte(
		"1\n00:00:00,000 --> 00:00:02,000\nhello\n\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	haveFFmpeg(t)
	path := filepath.Join(dir, "subs.mkv")
	out, err := exec.CommandContext(t.Context(), FFmpegPath, "-loglevel", "error", "-y",
		"-f", "lavfi", "-i", "testsrc=duration=2:size=320x180:rate=25",
		"-i", srt,
		"-c:v", "mpeg4", "-q:v", "5",
		"-c:s", "srt",
		"-metadata:s:s:0", "language=eng",
		path).CombinedOutput()
	if err != nil {
		t.Skipf("could not build the fixture (%v): %s", err, firstLine(out))
	}

	p := probeFile(t, path)
	if len(p.Subtitles) != 1 {
		t.Fatalf("%d subtitle streams, want 1: %+v", len(p.Subtitles), p.Subtitles)
	}
	s := p.Subtitles[0]
	if !s.Text {
		t.Errorf("an SRT track was not reported as text: %+v", s)
	}
	if s.Language != "eng" {
		t.Errorf("language = %q, want eng", s.Language)
	}

	// The other half of the claim, as a unit: the picture formats.
	for _, codec := range []string{"hdmv_pgs_subtitle", "dvd_subtitle", "dvb_subtitle", "xsub"} {
		if isTextSubtitle(codec) {
			t.Errorf("%s was reported as text; it is pictures, and a browser "+
				"cannot be handed it", codec)
		}
	}
}

// Cover art is a video stream as far as a container is concerned. Counting it
// would make an audio file look like it has a video track, and the first video
// stream picked for playback would be a JPEG.
func TestEmbeddedCoverArtIsNotAVideoTrack(t *testing.T) {
	dir := t.TempDir()
	haveFFmpeg(t)

	art := filepath.Join(dir, "art.png")
	if out, err := exec.CommandContext(t.Context(), FFmpegPath, "-loglevel", "error", "-y",
		"-f", "lavfi", "-i", "color=c=red:s=64x64:d=1", "-frames:v", "1",
		art).CombinedOutput(); err != nil {
		t.Skipf("could not build the cover (%v): %s", err, firstLine(out))
	}

	path := filepath.Join(dir, "withart.mp4")
	out, err := exec.CommandContext(t.Context(), FFmpegPath, "-loglevel", "error", "-y",
		"-f", "lavfi", "-i", "sine=frequency=440:duration=2",
		"-i", art,
		"-map", "0:a", "-map", "1:v",
		"-c:a", "aac", "-c:v", "copy",
		"-disposition:v:0", "attached_pic",
		path).CombinedOutput()
	if err != nil {
		t.Skipf("could not build the fixture (%v): %s", err, firstLine(out))
	}

	p := probeFile(t, path)
	if len(p.Video) != 0 {
		t.Errorf("cover art was counted as %d video track(s): %+v — an audio "+
			"file would look playable as video and the picture would be the "+
			"first stream chosen", len(p.Video), p.Video)
	}
	if len(p.Audio) != 1 {
		t.Errorf("%d audio streams, want 1", len(p.Audio))
	}
}

// Something that is not media must be a named refusal, not a zero-valued Probe
// that reads downstream as "a file with no streams".
func TestProbingSomethingThatIsNotMediaFails(t *testing.T) {
	haveFFmpeg(t)
	s := quietSandbox(t)

	path := filepath.Join(t.TempDir(), "notmedia.mkv")
	if err := os.WriteFile(path, []byte(strings.Repeat("not a video at all. ", 500)), 0o600); err != nil {
		t.Fatal(err)
	}
	f, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()

	if _, err := NewProber(s).Probe(context.Background(), f); err == nil {
		t.Fatal("probing a text file succeeded")
	}
}

// The probe is taken from a DESCRIPTOR the caller opened, so a caller holding
// only an fd — which is what os.Root hands out — can probe without anything in
// the system converting that back into a path.
func TestAProbeNeedsNothingButAnOpenFile(t *testing.T) {
	path := generate(t, "fd.mp4",
		"-f", "lavfi", "-i", "testsrc=duration=2:size=320x180:rate=25",
		"-c:v", "mpeg4", "-q:v", "5")
	s := quietSandbox(t)

	f, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	// Remove the file. The descriptor stays valid, so a probe that still works
	// is one that genuinely used the fd rather than re-opening a name.
	if err := os.Remove(path); err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()

	p, err := NewProber(s).Probe(context.Background(), f)
	if err != nil {
		t.Fatalf("probing an unlinked file through its descriptor: %v", err)
	}
	if len(p.Video) != 1 {
		t.Errorf("%d video streams from an unlinked file", len(p.Video))
	}
}

// Reading a header first must not cost the probe the start of the file.
func TestAProbeRewindsBeforeReading(t *testing.T) {
	path := generate(t, "rewind.mp4",
		"-f", "lavfi", "-i", "testsrc=duration=2:size=320x180:rate=25",
		"-c:v", "mpeg4", "-q:v", "5")
	s := quietSandbox(t)

	f, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()

	// Consume a header, as a magic-byte check would.
	if _, err := f.Read(make([]byte, 512)); err != nil {
		t.Fatal(err)
	}

	p, err := NewProber(s).Probe(context.Background(), f)
	if err != nil {
		t.Fatalf("probing after a partial read: %v", err)
	}
	if len(p.Video) != 1 {
		t.Errorf("%d video streams after a partial read — the descriptor was "+
			"not rewound", len(p.Video))
	}
}

// The composition ADR-0020 actually claims: a file opened through the library's
// os.Root can be probed, and the parser is still given nothing but the
// descriptor.
//
// The two halves are built separately and tested separately, and "these fit
// together" is the sort of thing that is obviously true right up until the
// signatures drift. Here it is asserted.
func TestAVaultedFileCanBeProbedThroughItsDescriptor(t *testing.T) {
	haveFFmpeg(t)
	s := quietSandbox(t)

	root := t.TempDir()
	// Generate into the directory the vault will own.
	out, err := exec.CommandContext(t.Context(), FFmpegPath, "-loglevel", "error", "-y",
		"-f", "lavfi", "-i", "testsrc=duration=2:size=320x180:rate=25",
		"-c:v", "mpeg4", "-q:v", "5",
		filepath.Join(root, "film.mp4")).CombinedOutput()
	if err != nil {
		t.Skipf("could not build the fixture (%v): %s", err, firstLine(out))
	}

	v, err := library.Open(1, root)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = v.Close() }()

	f, err := v.Open("film.mp4")
	if err != nil {
		t.Fatalf("opening through the vault: %v", err)
	}
	defer func() { _ = f.Close() }()

	p, err := NewProber(s).Probe(context.Background(), f)
	if err != nil {
		t.Fatalf("probing a vaulted file: %v", err)
	}
	if len(p.Video) != 1 {
		t.Errorf("%d video streams", len(p.Video))
	}

	// And the containment still holds: the vault refuses to hand out a
	// descriptor for anything outside it, so there is no descriptor to pass.
	if _, err := v.Open("../outside.mp4"); err == nil {
		t.Error("the vault opened a file above its root")
	}
}
